#!/bin/sh

ECLIPSE_FLAVOUR=$1
ACTION=$2

if [ -z "$ECLIPSE_FLAVOUR" ]; then
  echo You need to specify which Eclipse flavour you want.
  exit 1
fi

if [ -z "$ACTION" ]; then
  echo 'You need to specify what action you want (list, install).'
  exit 1
fi

if [ -e /etc/os-release ]; then
  . /etc/os-release
fi
if [ -e /etc/lsb-release ]; then
  . /etc/lsb-release
fi

if [ -z "$DISTRIB_ID" ]; then
  DISTRIB_ID=$ID
fi

if [ -z "$DISTRIB_ID" ]; then
  echo "No distribution found"
  exit 1
fi

if [ ! `which eclipse` ]; then
  if [ -z "$ECLIPSE_HOME" ]; then
    echo "Please set ECLIPSE_HOME to your Eclipse installation"
    exit 1
  else
    PATH=$PATH:$ECLIPSE_HOME
  fi
fi

#sudo yum install rh-eclipse46-base
# sudo yum install rh-eclipse46-eclipse-webtools-sourceediting

ORBIT_REPO=http://download.eclipse.org/tools/orbit/R-builds/R20170307180635/repository
M2EWTP_REPO=http://download.eclipse.org/m2e-wtp/releases/neon/
M2EAXISTOOLS_REPO=http://theit.github.com/m2e-lifecycle-axistools
M2EEXTRAS_REPO=https://repository.sonatype.org/content/repositories/forge-sites/m2e-extras/0.15.0/N/0.15.0.201206251206/
M2EMAVENDEV_REPO=http://ifedorenko.github.io/m2e-extras/
ECLEMMA_REPO=http://update.eclemma.org/
SONARLINT_REPO=http://eclipse.sonarlint.org/
DIRECTORYSTUDIO_REPO=http://directory.apache.org/studio/update/
CUCUMBER_REPO=https://cucumber.io/cucumber-eclipse/update-site
DBEAVER_REPO=http://dbeaver.jkiss.org/update/latest/
JBOSS_REPO=http://download.jboss.org/jbosstools/neon/stable/updates/
ORACLE_REPO=http://download.oracle.com/otn_software/oepe/12.2.1.5/neon/repository
MOREUNIT_REPO=http://moreunit.sourceforge.net/update-site/
SPRINGIDE_REPO=http://springide.org/updatesite
CSVEDIT_REPO=https://raw.githubusercontent.com/SegFaultError/CsvEdit/master/csvedit.update/
DECOMPILER_REPO=http://www.cpupk.com/decompiler/update
LICLIPSE_REPO=http://update.liclipse.com/latest
QWICKIE_REPO=http://raw.githubusercontent.com/count-negative/qwickie/master/qwickie.updatesite/site.xml

# broken repos
M2EJAXWS_REPO=http://coderplus.com/m2e-update-sites/jaxws-maven-plugin/

case $ECLIPSE_FLAVOUR in
  "java")
    REPOSITORIES=$ORBIT_REPO,$M2EWTP_REPO,$M2EAXISTOOLS_REPO,$M2EEXTRAS_REPO,$M2EJAXWS_REPO,$ECLEMMA_REPO,$SONARLINT_REPO,$DIRECTORYSTUDIO_REPO,$CUCUMBER_REPO,$M2EMAVENDEV_REPO,$DBEAVER_REPO,$JBOSS_REPO,$ORACLE_REPO,$MOREUNIT_REPO,$CSVEDIT_REPO,$DECOMPILER_REPO,$QWICKIE_REPO

    INSTALLIUS=\
org.eclipse.m2e.wtp.feature.feature.group,de.theit.m2e.axistools.feature.feature.group,org.sonatype.m2e.buildhelper.feature.feature.group,\
com.ifedorenko.m2e.mavendev.feature.feature.group,\
com.mountainminds.eclemma.feature.feature.group,org.sonarlint.eclipse.feature.feature.group,\
org.apache.directory.studio.ldapbrowser.feature.feature.group,\
org.jkiss.dbeaver.core.feature.feature.group,\
org.jkiss.dbeaver.ext.generic.feature.feature.group,\
org.jkiss.dbeaver.runtime.feature.feature.group,\
org.jkiss.dbeaver.ext.oracle.feature.feature.group,\
org.hibernate.eclipse.feature.feature.group,cucumber.eclipse.feature.feature.group,org.moreunit.feature.group,\
org.fhsolution.eclipse.feature.csvedit.feature.group,\
org.sf.feeling.decompiler.feature.group,\
qwickie.feature.feature.group

    if [ "$DISTRIB_ID" != "fedora" ]; then
        SUBCLIPSE_REPO=https://dl.bintray.com/subclipse/releases/subclipse/latest/
        M2E_REPO=http://download.eclipse.org/technology/m2e/releases
        REPOSITORIES=$REPOSITORIES,$SUBCLIPSE_REPO,$M2E_REPO
        INSTALLIUS=$INSTALLIUS,org.eclipse.m2e.feature.feature.group,org.tigris.subversion.subclipse.feature.group
    fi

    INSTALLIUS_NA=com.coderplus.m2e.jaxws.feature.group
    # sapphire too old
    INSTALLIUS_DEPS_NA=oracle.eclipse.tools.database.feature.group
    INSTALLIUS_BREAKS_ECLIPSE=org.springframework.ide.eclipse.feature.feature.group
    ;;
  "liclipse")
    REPOSITORIES=$LICLIPSE_REPO
    INSTALLIUS=com.brainwy.liclipse.feature.feature.group
    ;;
esac

COMMAND="eclipse -clean -purgeHistory -application org.eclipse.equinox.p2.director -noSplash -repository $REPOSITORIES"

case $ACTION in
  "list")
    ACTION=-list
  ;;
  "install")
    ACTION="-installIUs $INSTALLIUS"
  ;;
esac

case $DISTRIB_ID in
  "rhel")
    scl enable rh-eclipse46 "$COMMAND $ACTION"
    ;;
  *)
    $COMMAND $ACTION
    ;;
esac

# Lombok
lombok()
{
  if [ ! -e /opt/rh/rh-eclipse46/root/usr/local/lib/java/lombok.jar ]; then
    sudo mkdir -p /opt/rh/rh-eclipse46/root/usr/local/lib/java
    sudo wget https://projectlombok.org/downloads/lombok.jar -O /opt/rh/rh-eclipse46/root/usr/local/lib/java/lombok.jar
    sudo ln -s /opt/rh/rh-eclipse46/root/usr/local/lib/java/lombok.jar /opt/rh/rh-eclipse46/root/lib64/eclipse/
    echo '-javaagent:/opt/rh/rh-eclipse46/root/usr/local/lib/java/lombok.jar' | sudo tee -a /opt/rh/rh-eclipse46/root/etc/eclipse.ini
  fi
}
